version: '3.1'

services:

  postgres:
    container_name: nodejs2023Q2-service-postgres
    image: thirdmadman/nodejs2023q2-service-postgres-dev
    build: 
      dockerfile: ./.docker/postgres.dockerfile
    restart: always
    networks:
      - postgres
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres_logs:/logs
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/logs

  web:
    container_name: nodejs2023Q2-service-app
    image: thirdmadman/nodejs2023q2-service-app-dev
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL_DOCKER}
    build: 
      dockerfile: ./.docker/node.dockerfile
      target: install
    command:
      - /bin/sh
      - -c
      - |
        npx prisma migrate deploy
        npm run start:dev
    volumes:
      - ./src:/usr/app/src
      - node_modules_dev:/usr/app/node_modules
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    networks:
      - postgres
    restart: always

volumes:
  postgres-data:
  postgres_logs:
  node_modules_dev:

networks:
  postgres:
    driver: bridge