version: '3.1'

services:

  postgres:
    image: postgres:alpine
    restart: on-failure
    networks:
      - postgres
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres_logs:/logs

  web:
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL_DOCKER}
    build: 
      dockerfile: ./.docker/node.dockerfile
    command:
      - /bin/sh
      - -c
      - |
        npx prisma migrate deploy
        npm run start:prod
    volumes:
      - app-dist:/usr/app/dist/
      - node_modules:/usr/app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    networks:
      - postgres

volumes:
  postgres-data:
  postgres_logs:
  app-dist:
  node_modules:

networks:
  postgres:
    driver: bridge