version: '3.1'

services:

  postgres:
    image: postgres
    restart: on-failure
    networks:
      - postgres
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres_logs:/logs
    ports:
      - "5432:5432"

  web:
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL_DOCKER}
    build: 
      dockerfile: ./.docker/node.dockerfile
      target: install
    command:
      - /bin/sh
      - -c
      - |
        npx prisma migrate deploy
        npm run start:dev
    volumes:
      - ./src:/usr/app/src
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    networks:
      - postgres

volumes:
  postgres-data:
  postgres_logs:
  node_modules:

networks:
  postgres:
    driver: bridge