version: '3.1'

services:

  postgres:
    container_name: nodejs2023Q2-service-postgres
    image: thirdmadman/nodejs2023q2-service-postgres
    build: 
      dockerfile: ./.docker/postgres.dockerfile
    restart: on-failure
    networks:
      - postgres
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres_logs:/logs

  web:
    container_name: nodejs2023Q2-service-app
    image: thirdmadman/nodejs2023q2-service-app
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL_DOCKER}
    build: 
      dockerfile: ./.docker/node.dockerfile
    command:
      - /bin/sh
      - -c
      - |
        npx prisma migrate deploy
        npm run start:prod
    volumes:
      - app-dist:/usr/app/dist/
      - node_modules:/usr/app/node_modules
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    networks:
      - postgres
    restart: on-failure

volumes:
  postgres-data:
  postgres_logs:
  app-dist:
  node_modules:

networks:
  postgres:
    driver: bridge