version: '3.1'

services:

  postgres:
    image: postgres:18-alpine
    restart: on-failure
    networks:
      - postgres
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_DB: todos
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres_logs:/logs

  web:
    build: 
      dockerfile: ./.docker/node.dockerfile
    command: npm run start:prod
    volumes:
      - app-dist:/usr/app/dist
      - node_modules:/usr/app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://todoapp@postgres/todos
    networks:
      - postgres

volumes:
  postgres-data:
  postgres_logs:
  app-dist:
  node_modules:

networks:
  postgres:
    driver: bridge